### ISSUE TITLE
Clarification on the script and steps for reproducing Figure 6. in the paper

### ISSUE THREAD

**Issue by kftam1994** [Andrew-Draganov/dc_dist#1]
Thanks for the implementation code of your paper
I would like to reproduce Figure 6. in the paper and then try it in other datasets such as text content's embeddings
Should I run the RealDataClusterings.py but it seems expClusteringComparisonRealData() function does not output the chart?
Would you mind specifying the steps for reproducing Figure 6. from dataset processing in DimReduceDatasets.py to clustering in RealDataClusterings.py?
Thank you

**Comment by Andrew-Draganov** [comment]
Ah, right. Figure 6 is likely the most difficult to recreate in this codebase, so I apologize for that. To do it, you need to run `expClusteringComparisonRealData()` and save the ARIs (uncomment the last line in the method to do so). After that, you can run `createRealPlot` using those ARI save files. Let me know if that helps or if you have other questions.

**Comment by kftam1994** [comment]
Thanks Andrew for your response
I would like to conduct kcenter clustering on dc-dist for data with dimension > 2 but saw that cluster_tree.dc_clustering() (or its previous step density_tree.make_tree() actually) only handles points with 2 dimensions.
Is my understanding correct as Figure 4 shows distribution of distance for clustering data of multiple dimensions > 2?
Thank you

**Comment by Andrew-Draganov** [comment]
Hi, is there a place you can point to that requires two dimensions? If you mean [this line](https://github.com/Andrew-Draganov/dc_dist/blob/master/density_tree.py#L108), we just require that the points.shape has length 2 meaning that it is an nxd matrix (where n is the number of points and d is the dimensionality). But the dimensionality itself can be anything, unless I'm mistaken.

**Comment by kftam1994** [comment]
Thanks for the clarification. Yes it is my misunderstanding.
